# -*- coding: utf-8 -*-
"""censored_words_blocker.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kntGEDtUj9vtYejg63E48W11sjdRvgK7
"""

2+7

pip install  better_profanity

from better_profanity import profanity

text=input()
censored= profanity.censor(text)
print(censored)